version: '3'
services:
  app:
    container_name: node-docker-app
    restart: always
    build: .
    command: nodemon --inspect-brk=0.0.0.0:9229
    volumes:
      - .:/var/www/app
    ports:
      - '80:3000'
      - '9229:9229'